### ISSUE TITLE
Running sample code from README.md: RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by linus-git** [microsoftgraph/msgraph-sdk-python#114]
**Python 3.9.9
msgraph-sdk  1.0.0a9**

When I'm Running the sample code from chapter 3 in README.md the result is correct but additionally following error is returned:

```
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000026331A6F1F0>
Traceback (most recent call last):
  File "C:\Users\SLEINEK\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\SLEINEK\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\SLEINEK\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\SLEINEK\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000026331A6F1F0>
Traceback (most recent call last):
  File "C:\Users\SLEINEK\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\SLEINEK\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\SLEINEK\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Users\SLEINEK\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
``'

Can someone help me out here?

**Comment by isvargasmsft** [comment]
Hello @linus-git, would you be so kind to try-catch the code like this:

```py
async def get_user():
    try:
        user = await client.users_by_id('userID').get()
        print(user.user_principal_name, user.display_name, user.id)
    except Exception as e:
        print(f'Error: {e.error.message}')

asyncio.run(get_user())
```

Please share the error message you are receiving.

**Comment by linus-git** [comment]
Hello Issac, 

thank you for your response!

I added 2 print statements to the code. They show, that the code does not reach the except suite.

```
async def get_user():
    try:
        user = await client.users_by_id('sleinek@emea.corpdir.net').get()
        print(user.user_principal_name, user.display_name, user.id)
        print("End of try")
    except Exception as e:
        print("Begin of except")
        print(f'Error: {e.error.message}')
```


Response: 

```
C:\GitHub\alias-service\venv\Scripts\python.exe  sl_work.py
sleinek@emea.corpdir.net Lackig, Mario (415) c485748d-ca3a-4fdc-b80e-91122eaad206
End of try

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000017EDAA001F0>
Traceback (most recent call last):
  File "C:\Users\SLEINEK\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\SLEINEK\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\SLEINEK\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\SLEINEK\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000017EDAA001F0>
Traceback (most recent call last):
  File "C:\Users\SLEINEK\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\SLEINEK\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\SLEINEK\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Users\SLEINEK\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
```

Best regrads, 
Stefan

**Comment by isvargasmsft** [comment]
Hi @linus-git,

It seems like your request is passing successfully. I did a quick search and it seems to be something with your asyncio configuration. 
Please double check that your asyncio is properly configured. An example:
```py
# pylint: disable=no-member

import asyncio

from azure.identity.aio import ClientSecretCredential
from kiota_authentication_azure.azure_identity_authentication_provider import AzureIdentityAuthenticationProvider

from msgraph import GraphRequestAdapter
from msgraph import GraphServiceClient

asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

# Create auth proviver object. Used to authenticate request

credential = ClientSecretCredential("{tenantID}",
                                    "{appID}",
                                    "clientSecret")
scopes = ['https://graph.microsoft.com/.default']
auth_provider = AzureIdentityAuthenticationProvider(credential, scopes=scopes)

# Initialize a request adapter. Handles the HTTP concerns
request_adapter = GraphRequestAdapter(auth_provider)

# Get a service client
client = GraphServiceClient(request_adapter)

# GET emails from user
async def get_user_messages():
    """Getting the messages of a user"""
    try:
        messages = await client.users_by_id("{userID}").messages.get()
        for msg in messages.value:
            print(
                msg.subject,
                msg.id,
            )
    except Exception as e_rr:
        print(f'Error: {e_rr.error.message}')

asyncio.run(get_user_messages())
```

Please let me know if this helps.

**Comment by linus-git** [comment]
Hi Isaac,

you are right. It was the asyncio configuration. Now everything's fine. 
Thank you very much for your support! Sorry for bothering you. 

Best regards,
Stefan
