### ISSUE TITLE
NameError: name 'Guid' is not defined

### ISSUE THREAD

**Issue by yoshigev** [microsoftgraph/msgraph-sdk-python#115]
Hi,

I'm trying to perform `service_principals.get()` and the following exception is thrown:
```
Traceback (most recent call last):
  File "./tests/test_components/test_guid.py", line 36, in <module>
    asyncio.run(run())
  File "C:\Program Files\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "./tests/test_components/test_guid.py", line 33, in run
    res = await graph.get_service_principals()
  File "./tests/test_components/test_guid.py", line 27, in get_service_principals
    res = await self.user_client.service_principals.get()
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\msgraph\generated\service_principals\service_principals_request_builder.py", line 95, in get
    return await self.request_adapter.send_async(request_info, service_principal_collection_response.ServicePrincipalCollectionResponse, error_mapping)
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\kiota_http\httpx_request_adapter.py", line 122, in send_async
    result = root_node.get_object_value(model_type)
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\kiota_serialization_json\json_parse_node.py", line 226, in get_object_value
    self._assign_field_values(result)
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\kiota_serialization_json\json_parse_node.py", line 287, in _assign_field_values
    deserializer(JsonParseNode(val))
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\msgraph\generated\models\service_principal_collection_response.py", line 36, in <lambda>
    "value": lambda n : setattr(self, 'value', n.get_collection_of_object_values(service_principal.ServicePrincipal)),
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\kiota_serialization_json\json_parse_node.py", line 181, in get_collection_of_object_values
    self._json_node
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\kiota_serialization_json\json_parse_node.py", line 180, in <lambda>
    lambda x: JsonParseNode(x).get_object_value(factory),  # type: ignore
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\kiota_serialization_json\json_parse_node.py", line 226, in get_object_value
    self._assign_field_values(result)
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\kiota_serialization_json\json_parse_node.py", line 287, in _assign_field_values
    deserializer(JsonParseNode(val))
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\msgraph\generated\models\service_principal.py", line 495, in <lambda>
    "app_owner_organization_id": lambda n : setattr(self, 'app_owner_organization_id', n.get_object_value(Guid)),
NameError: name 'Guid' is not defined
```

This is the code for reproduction:
```python
import asyncio
from azure.identity import UsernamePasswordCredential
from kiota_authentication_azure.azure_identity_authentication_provider import (AzureIdentityAuthenticationProvider)
from msgraph import GraphRequestAdapter, GraphServiceClient


class Graph:
    adapter: GraphRequestAdapter
    user_client: GraphServiceClient

    def __init__(self):
        default_client_id = 'xxx'
        admin_username = 'xxx'
        admin_password = 'xxx'
        tenant_id = 'xxx'

        credential = UsernamePasswordCredential(client_id=default_client_id,
                                                username=admin_username,
                                                password=admin_password,
                                                tenant_id=tenant_id)
        auth_provider = AzureIdentityAuthenticationProvider(
            credential)
        self.adapter = GraphRequestAdapter(auth_provider)
        self.user_client = GraphServiceClient(self.adapter)

    async def get_service_principals(self):
      res = await self.user_client.service_principals.get()
      return res.value


async def run():
    graph = Graph()
    res = await graph.get_service_principals()
    print(res)

asyncio.run(run())
```

The following relevant packages are installed:
```
Package                              Version
------------------------------------ -----------
azure-core                           1.25.0
azure-identity                       1.12.0
microsoft-kiota-abstractions         0.4.0
microsoft-kiota-authentication-azure 0.2.0
microsoft-kiota-http                 0.4.0
microsoft-kiota-serialization-json   0.2.2
microsoft-kiota-serialization-text   0.2.0
msgraph-core                         1.0.0a4
msgraph-sdk                          1.0.0a9
```

**Comment by benoit74** [comment]
Same issue here, "Guid" type is used everywhere in generated models ...

**Comment by DrKabum** [comment]
Same issue here. There should be no issue for `self.user_client.users.get()` or `self.user_client.groups.get()` though in your example (it works for these two for me), but `service_principals`, `devices`, `applications` all raise this error

**Comment by DrKabum** [comment]
Actually, for anyone interested, I managed to work around it on my side. My understanding is that the library is asking for a `Guid` field that is not defined in the API for service principals that are not users or groups (or something. This field doesn't exist in our case at least).

So you need to use query parameters to specify only fields that are interesting for you, excluding `Guid`. That would look like that in you example:

```python
# add this import:
from msgraph.generated.service_principals.service_principals_request_builder import ServicePrincipalsRequestBuilder

# ... Don't need to change anything to your constructor

# make these changes to the following function
async def get_service_principals(self):
      query_params = ServicePrincipalsRequestBuilder.ServicePrincipalsRequestBuilderGetQueryParameters(
            select=["displayName", "id"] # that's where you select the fields you want. I believe this overrides the broken defaults from the library
        )
        request_configuration = ServicePrincipalsRequestBuilder.ServicePrincipalsRequestBuilderGetRequestConfiguration(
            query_parameters=query_params
        )
      res = await self.user_client.service_principals.get(request_configuration=request_configuration)
      return res.value
```

It fixed it for me, let me know if you guys need more info.

PS: I think I eventually cleaned the million of typos in there. Kinda adapted it from my own code on the fly, sorry for that

**Comment by samwelkanda** [comment]
Hello @yoshigev @benoit74 @DrKabum 

Thanks for trying out our SDK. The above issue has been fixed in the generated code. `Guid` is now mapped to Python's `UUID` type which should resolve the issues you are facing. Please update to the latest release to get the changes

Thanks!
