### ISSUE TITLE
Expanding "members" property of a Group raise an exception

### ISSUE THREAD

**Issue by phenixdotnet** [microsoftgraph/msgraph-sdk-python#151]
Hi

Looks like trying to retrieve the members of an Azure AD group with the group using the OData property `expand` raise an exception when the group contains at least 1 user:

```
INFO:azure.identity._internal.get_token_mixin:ClientSecretCredential.get_token succeeded
DEBUG:httpx._client:HTTP Request: GET https://graph.microsoft.com/beta/groups/983XXXXXXXXX5b6c?$expand=members "HTTP/1.1 200 OK"
NameError("name 'u_u_i_d' is not defined")
Traceback (most recent call last):
  File "./src/main.py", line 77, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "./src/main.py", line 29, in main
    await ring_manager.init()
  File "src/ringmanager.py", line 22, in init
    self.ring_groups = await self._load_ring_groups()
  File "src/ringmanager.py", line 55, in _load_ring_groups
    group = await self.msGraph.get_group_from_id(ring_id)
  File "src/graph.py", line 135, in get_group_from_id
    group = await self.client.groups_by_id(group_id).get(request_config)
  File ".venv/lib/python3.10/site-packages/msgraph/generated/groups/item/group_item_request_builder.py", line 252, in get
    return await self.request_adapter.send_async(request_info, group.Group, error_mapping)
  File ".venv/lib/python3.10/site-packages/kiota_http/httpx_request_adapter.py", line 122, in send_async
    result = root_node.get_object_value(model_type)
  File ".venv/lib/python3.10/site-packages/kiota_serialization_json/json_parse_node.py", line 226, in get_object_value
    self._assign_field_values(result)
  File ".venv/lib/python3.10/site-packages/kiota_serialization_json/json_parse_node.py", line 285, in _assign_field_values
    deserializer(JsonParseNode(val))
  File ".venv/lib/python3.10/site-packages/msgraph/generated/models/group.py", line 523, in <lambda>
    "members": lambda n : setattr(self, 'members', n.get_collection_of_object_values(directory_object.DirectoryObject)),
  File ".venv/lib/python3.10/site-packages/kiota_serialization_json/json_parse_node.py", line 178, in get_collection_of_object_values
    return list(
  File ".venv/lib/python3.10/site-packages/kiota_serialization_json/json_parse_node.py", line 180, in <lambda>
    lambda x: JsonParseNode(x).get_object_value(factory),  # type: ignore
  File ".venv/lib/python3.10/site-packages/kiota_serialization_json/json_parse_node.py", line 226, in get_object_value
    self._assign_field_values(result)
  File ".venv/lib/python3.10/site-packages/kiota_serialization_json/json_parse_node.py", line 285, in _assign_field_values
    deserializer(JsonParseNode(val))
  File ".venv/lib/python3.10/site-packages/msgraph/generated/models/user.py", line 1033, in <lambda>
    "assignedLicenses": lambda n : setattr(self, 'assigned_licenses', n.get_collection_of_object_values(assigned_license.AssignedLicense)),
  File ".venv/lib/python3.10/site-packages/kiota_serialization_json/json_parse_node.py", line 178, in get_collection_of_object_values
    return list(
  File ".venv/lib/python3.10/site-packages/kiota_serialization_json/json_parse_node.py", line 180, in <lambda>
    lambda x: JsonParseNode(x).get_object_value(factory),  # type: ignore
  File ".venv/lib/python3.10/site-packages/kiota_serialization_json/json_parse_node.py", line 226, in get_object_value
    self._assign_field_values(result)
  File ".venv/lib/python3.10/site-packages/kiota_serialization_json/json_parse_node.py", line 285, in _assign_field_values
    deserializer(JsonParseNode(val))
  File ".venv/lib/python3.10/site-packages/msgraph/generated/models/assigned_license.py", line 73, in <lambda>
    "disabledPlans": lambda n : setattr(self, 'disabled_plans', n.get_collection_of_primitive_values(u_u_i_d)),
NameError: name 'u_u_i_d' is not defined
```

Repro steps:
Retrieve a group by id and specify the `expand` property with `members` value
```python
query_params = GroupItemRequestBuilder.GroupItemRequestBuilderGetQueryParameters(expand=['members'])
request_config = GroupItemRequestBuilder.GroupItemRequestBuilderGetRequestConfiguration(query_parameters=query_params)
group = await self.client.groups_by_id(group_id).get(request_config)
return group
```
(`self.client` is a `GraphServiceClient` instance)

Removing the `expand=['members']` property allow the group to be loaded correctly

**Comment by samwelkanda** [comment]
@phenixdotnet Thanks for submitting the issue. 

The bug has been fixed. Please update to the latest version `1.0.0a11` and let us know if you face any further challenges.

**Comment by phenixdotnet** [comment]
Hi, Thanks I will test it ASAP 👍
