### ISSUE TITLE
 `AttributeError: 'Request' object has no attribute 'options'` when trying to get DriveItem content.

### ISSUE THREAD

**Issue by ruckc** [microsoftgraph/msgraph-sdk-python#198]
**Describe the bug**
`AttributeError: 'Request' object has no attribute 'options'` when trying to get DriveItem content.

**To Reproduce**
```python
data = await client.drives.by_drive_id(drive_id).items.by_drive_item_id(item_id).content.get()
```

**Expected behavior**
retrieved `bytes` object from DriveItem

**Additional context**
***relevant package versions***
```sh
$ pip list |grep -E "^(azure|micro|ms)"
azure-core                           1.26.4
azure-identity                       1.12.0
microsoft-kiota-abstractions         0.5.1
microsoft-kiota-authentication-azure 0.2.0
microsoft-kiota-http                 0.4.1
microsoft-kiota-serialization-json   0.3.2
microsoft-kiota-serialization-text   0.2.0
msal                                 1.22.0
msal-extensions                      1.0.0
msgraph-core                         1.0.0a4
msgraph-sdk                          1.0.0a12
```
***stacktrace***
```
  File "/home/user/example/example/microsoft365.py", line 66, in __walk_folder
    file_data = await client.drives.by_drive_id(drive_id).items.by_drive_item_id(item.id).content.get()
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/msgraph/generated/drives/item/items/item/content/content_request_builder.py", line 56, in get
    return await self.request_adapter.send_primitive_async(request_info, "bytes", error_mapping)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/kiota_http/httpx_request_adapter.py", line 205, in send_primitive_async
    response = await self.get_http_response_message(request_info)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/kiota_http/httpx_request_adapter.py", line 320, in get_http_response_message
    resp = await self._http_client.send(request)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/msgraph_core/middleware/async_graph_transport.py", line 21, in handle_async_request
    response = await self.pipeline.send(request)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 31, in send
    return await self._first_middleware.send(request, self._transport)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/kiota_http/middleware/redirect_handler.py", line 65, in send
    response = await super().send(request, transport)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 57, in send
    return await self.next.send(request, transport)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/kiota_http/middleware/retry_handler.py", line 77, in send
    response = await super().send(request, transport)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 57, in send
    return await self.next.send(request, transport)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/kiota_http/middleware/parameters_name_decoding_handler.py", line 48, in send
    response = await super().send(request, transport)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 57, in send
    return await self.next.send(request, transport)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/msgraph_core/middleware/telemetry.py", line 48, in send
    response = await super().send(request, transport)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 54, in send
    response = await transport.handle_async_request(request)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/msgraph_core/middleware/async_graph_transport.py", line 21, in handle_async_request
    response = await self.pipeline.send(request)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 31, in send
    return await self._first_middleware.send(request, self._transport)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/kiota_http/middleware/redirect_handler.py", line 65, in send
    response = await super().send(request, transport)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 57, in send
    return await self.next.send(request, transport)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/kiota_http/middleware/retry_handler.py", line 68, in send
    current_options = self._get_current_options(request)
  File "/home/user/.cache/pypoetry/virtualenvs/example-r_fbvPX4-py3.10/lib/python3.10/site-packages/kiota_http/middleware/retry_handler.py", line 111, in _get_current_options
    request_options = request.options.get(RetryHandlerOption.get_key())  # type:ignore
AttributeError: 'Request' object has no attribute 'options'
```

**Comment by tpcgold** [comment]
this issue still exists!
```
async def get_drive_items():
    items = await client.drives.by_drive_id(
        "DRIVE_ID"
    ).items.get()
    if items and items.value:
        for item in items.value:
            print(item.id, item.name, item.size, item.folder, item.file)

asyncio.run(get_drive_items())
```

```
Traceback (most recent call last):
  File "/Users/tpcgold/PycharmProjects/data-etl/venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3548, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-24620e72fe8f>", line 156, in <module>
    asyncio.run(get_drive_items())
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "<ipython-input-3-24620e72fe8f>", line 148, in get_drive_items
    items = await client.drives.by_drive_id(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tpcgold/PycharmProjects/data-etl/venv/lib/python3.11/site-packages/msgraph/generated/drives/item/items/items_request_builder.py", line 65, in get
    return await self.request_adapter.send_async(request_info, DriveItemCollectionResponse, error_mapping)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tpcgold/PycharmProjects/data-etl/venv/lib/python3.11/site-packages/kiota_http/httpx_request_adapter.py", line 178, in send_async
    response = await self.get_http_response_message(request_info, parent_span)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tpcgold/PycharmProjects/data-etl/venv/lib/python3.11/site-packages/kiota_http/httpx_request_adapter.py", line 528, in get_http_response_message
    resp = await self._http_client.send(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tpcgold/PycharmProjects/data-etl/venv/lib/python3.11/site-packages/httpx/_client.py", line 1646, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tpcgold/PycharmProjects/data-etl/venv/lib/python3.11/site-packages/httpx/_client.py", line 1674, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tpcgold/PycharmProjects/data-etl/venv/lib/python3.11/site-packages/httpx/_client.py", line 1711, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tpcgold/PycharmProjects/data-etl/venv/lib/python3.11/site-packages/httpx/_client.py", line 1748, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tpcgold/PycharmProjects/data-etl/venv/lib/python3.11/site-packages/msgraph_core/middleware/async_graph_transport.py", line 21, in handle_async_request
    response = await self.pipeline.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tpcgold/PycharmProjects/data-etl/venv/lib/python3.11/site-packages/kiota_http/middleware/middleware.py", line 38, in send
    return await self._first_middleware.send(request, self._transport)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tpcgold/PycharmProjects/data-etl/venv/lib/python3.11/site-packages/kiota_http/middleware/redirect_handler.py", line 77, in send
    response = await super().send(request, transport)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tpcgold/PycharmProjects/data-etl/venv/lib/python3.11/site-packages/kiota_http/middleware/middleware.py", line 65, in send
    return await self.next.send(request, transport)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tpcgold/PycharmProjects/data-etl/venv/lib/python3.11/site-packages/kiota_http/middleware/retry_handler.py", line 83, in send
    response = await super().send(request, transport)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tpcgold/PycharmProjects/data-etl/venv/lib/python3.11/site-packages/kiota_http/middleware/middleware.py", line 65, in send
    return await self.next.send(request, transport)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tpcgold/PycharmProjects/data-etl/venv/lib/python3.11/site-packages/kiota_http/middleware/parameters_name_decoding_handler.py", line 62, in send
    response = await super().send(request, transport)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tpcgold/PycharmProjects/data-etl/venv/lib/python3.11/site-packages/kiota_http/middleware/middleware.py", line 65, in send
    return await self.next.send(request, transport)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tpcgold/PycharmProjects/data-etl/venv/lib/python3.11/site-packages/kiota_http/middleware/url_replace_handler.py", line 38, in send
    current_options = self._get_current_options(request)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tpcgold/PycharmProjects/data-etl/venv/lib/python3.11/site-packages/kiota_http/middleware/url_replace_handler.py", line 58, in _get_current_options
    current_options = request.options.get(  # type:ignore
                      ^^^^^^^^^^^^^^^
AttributeError: 'Request' object has no attribute 'options'
```
