### ISSUE TITLE
Copy assigning a FileAttachment list hangs

### ISSUE THREAD

**Issue by jussihi** [microsoftgraph/msgraph-sdk-python#350]
Copy assigning a FileAttachment list from `attachments.get()` to a `Message` instance fails for some attachment files, but not all.

For example, the following code is problematic:

```python
for new_message in messages:
    try:
        attachments = (await (graph_client.users.by_user_id(user_id).messages.by_message_id(new_message.id).attachments.get())).value
        if attachments is None:
            print("something weird happened, there should be an attachment list")
        new_message.attachments = attachments
```

The code hangs on the last row. When ctrl+C out of the program, the trace is:

```
^C^CDEBUG:asyncio:Close <_UnixSelectorEventLoop running=False closed=False debug=True>
Traceback (most recent call last):
  File "/home/jussi/testi/graph-mail/main.py", line 41, in <module>
    asyncio.run(main(), debug=True)
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1914, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/jussi/testi/graph-mail/AutoLeadGraphAPI.py", line 57, in process_single_mailbox
    new_message.attachments = attachments
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/backed_model.py", line 31, in __setattr__
    self.backing_store.set(prop, val)
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 112, in set
    self.__subscriptions[sub](key, old_value, value_to_add)
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 107, in <lambda>
    lambda prop_key, old_val, new_val: self.set(key, value)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 105, in set
    item.backing_store.is_initialization_completed = True
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 38, in is_initialization_completed
    self._ensure_collection_size_is_consistent(key, val[1])
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 196, in _ensure_collection_size_is_consistent
    self.set(key, entry[0])  # dirty track the change
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 112, in set
    self.__subscriptions[sub](key, old_value, value_to_add)
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 107, in <lambda>
    lambda prop_key, old_val, new_val: self.set(key, value)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 105, in set
    item.backing_store.is_initialization_completed = True
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 38, in is_initialization_completed
    self._ensure_collection_size_is_consistent(key, val[1])
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 196, in _ensure_collection_size_is_consistent
    self.set(key, entry[0])  # dirty track the change
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 112, in set
    self.__subscriptions[sub](key, old_value, value_to_add)
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 107, in <lambda>
    lambda prop_key, old_val, new_val: self.set(key, value)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 105, in set
    item.backing_store.is_initialization_completed = True
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 38, in is_initialization_completed
    self._ensure_collection_size_is_consistent(key, val[1])
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 203, in _ensure_collection_size_is_consistent
    entry.backing_store.get(value[0])
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 70, in get
    if self.return_only_changed_values is False or (
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 41, in return_only_changed_values
    @property

  File "/usr/lib/python3.11/asyncio/runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt
```

Attachment list printed out to stdout:
```
[FileAttachment(additional_data={'@odata.mediaContentType': 'application/octet-stream'}, id='...', odata_type='#microsoft.graph.fileAttachment', content_type='application/octet-stream', is_inline=False, last_modified_date_time=datetime.datetime(2023, 9, 15, 12, 57, 11, tzinfo=tzutc()), name='sample.pdf', size=3336, content_bytes=b'JVBERi0xLjMNCiXi48/TDQoNCjEgMCBvYmoNCjw8DQovVHlwZSAvQ2F0YWxvZw0KL091dGxpbmVzIDIgMCBSDQovUGFnZXMgMyAwIFINCj4+DQplbmRvYmoNCg0KMiAwIG9iag0KPDwNCi9UeXBlIC9PdXRsaW5lcw0KL0NvdW50IDANCj4+DQplbmRvYmoNCg0KMyAwIG9iag0KPDwNCi9UeXBlIC9QYWdlcw0KL0NvdW50IDINCi9LaWRzIFsgNCAwIFIgNiAwIFIgXSANCj4+DQplbmRvYmoNCg0KNCAwIG9iag0KPDwNCi9UeXBlIC9QYWdlDQovUGFyZW50IDMgMCBSDQovUmVzb3VyY2VzIDw8DQovRm9udCA8PA0KL0YxIDkgMCBSIA0KPj4NCi9Qcm9jU2V0IDggMCBSDQo+Pg0KL01lZGlhQm94IFswIDAgNjEyLjAwMDAgNzkyLjAwMDBdDQovQ29udGVudHMgNSAwIFINCj4+DQplbmRvYmoNCg0KNSAwIG9iag0KPDwgL0xlbmd0aCAxMDc0ID4+DQpzdHJlYW0NCjIgSg0KQlQNCjAgMCAwIHJnDQovRjEgMDAyNyBUZg0KNTcuMzc1MCA3MjIuMjgwMCBUZA0KKCBBIFNpbXBsZSBQREYgRmlsZSApIFRqDQpFVA0KQlQNCi9GMSAwMDEwIFRmDQo2OS4yNTAwIDY4OC42MDgwIFRkDQooIFRoaXMgaXMgYSBzbWFsbCBkZW1vbnN0cmF0aW9uIC5wZGYgZmlsZSAtICkgVGoNCkVUDQpCVA0KL0YxIDAwMTAgVGYNCjY5LjI1MDAgNjY0LjcwNDAgVGQNCigganVzdCBmb3IgdXNlIGluIHRoZSBWaXJ0dWFsIE1lY2hhbmljcyB0dXRvcmlhbHMuIE1vcmUgdGV4dC4gQW5kIG1vcmUgKSBUag0KRVQNCkJUDQovRjEgMDAxMCBUZg0KNjkuMjUwMCA2NTIuNzUyMCBUZA0KKCB0ZXh0LiBBbmQgbW9yZSB0ZXh0LiBBbmQgbW9yZSB0ZXh0LiBBbmQgbW9yZSB0ZXh0LiApIFRqDQpFVA0KQlQNCi9GMSAwMDEwIFRmDQo2OS4yNTAwIDYyOC44NDgwIFRkDQooIEFuZCBtb3JlIHRleHQuIEFuZCBtb3JlIHRleHQuIEFuZCBtb3JlIHRleHQuIEFuZCBtb3JlIHRleHQuIEFuZCBtb3JlICkgVGoNCkVUDQpCVA0KL0YxIDAwMTAgVGYNCjY5LjI1MDAgNjE2Ljg5NjAgVGQNCiggdGV4dC4gQW5kIG1vcmUgdGV4dC4gQm9yaW5nLCB6enp6ei4gQW5kIG1vcmUgdGV4dC4gQW5kIG1vcmUgdGV4dC4gQW5kICkgVGoNCkVUDQpCVA0KL0YxIDAwMTAgVGYNCjY5LjI1MDAgNjA0Ljk0NDAgVGQNCiggbW9yZSB0ZXh0LiBBbmQgbW9yZSB0ZXh0LiBBbmQgbW9yZSB0ZXh0LiBBbmQgbW9yZSB0ZXh0LiBBbmQgbW9yZSB0ZXh0LiApIFRqDQpFVA0KQlQNCi9GMSAwMDEwIFRmDQo2OS4yNTAwIDU5Mi45OTIwIFRkDQooIEFuZCBtb3JlIHRleHQuIEFuZCBtb3JlIHRleHQuICkgVGoNCkVUDQpCVA0KL0YxIDAwMTAgVGYNCjY5LjI1MDAgNTY5LjA4ODAgVGQNCiggQW5kIG1vcmUgdGV4dC4gQW5kIG1vcmUgdGV4dC4gQW5kIG1vcmUgdGV4dC4gQW5kIG1vcmUgdGV4dC4gQW5kIG1vcmUgKSBUag0KRVQNCkJUDQovRjEgMDAxMCBUZg0KNjkuMjUwMCA1NTcuMTM2MCBUZA0KKCB0ZXh0LiBBbmQgbW9yZSB0ZXh0LiBBbmQgbW9yZSB0ZXh0LiBFdmVuIG1vcmUuIENvbnRpbnVlZCBvbiBwYWdlIDIgLi4uKSBUag0KRVQNCmVuZHN0cmVhbQ0KZW5kb2JqDQoNCjYgMCBvYmoNCjw8DQovVHlwZSAvUGFnZQ0KL1BhcmVudCAzIDAgUg0KL1Jlc291cmNlcyA8PA0KL0ZvbnQgPDwNCi9GMSA5IDAgUiANCj4+DQovUHJvY1NldCA4IDAgUg0KPj4NCi9NZWRpYUJveCBbMCAwIDYxMi4wMDAwIDc5Mi4wMDAwXQ0KL0NvbnRlbnRzIDcgMCBSDQo+Pg0KZW5kb2JqDQoNCjcgMCBvYmoNCjw8IC9MZW5ndGggNjc2ID4+DQpzdHJlYW0NCjIgSg0KQlQNCjAgMCAwIHJnDQovRjEgMDAyNyBUZg0KNTcuMzc1MCA3MjIuMjgwMCBUZA0KKCBTaW1wbGUgUERGIEZpbGUgMiApIFRqDQpFVA0KQlQNCi9GMSAwMDEwIFRmDQo2OS4yNTAwIDY4OC42MDgwIFRkDQooIC4uLmNvbnRpbnVlZCBmcm9tIHBhZ2UgMS4gWWV0IG1vcmUgdGV4dC4gQW5kIG1vcmUgdGV4dC4gQW5kIG1vcmUgdGV4dC4gKSBUag0KRVQNCkJUDQovRjEgMDAxMCBUZg0KNjkuMjUwMCA2NzYuNjU2MCBUZA0KKCBBbmQgbW9yZSB0ZXh0LiBBbmQgbW9yZSB0ZXh0LiBBbmQgbW9yZSB0ZXh0LiBBbmQgbW9yZSB0ZXh0LiBBbmQgbW9yZSApIFRqDQpFVA0KQlQNCi9GMSAwMDEwIFRmDQo2OS4yNTAwIDY2NC43MDQwIFRkDQooIHRleHQuIE9oLCBob3cgYm9yaW5nIHR5cGluZyB0aGlzIHN0dWZmLiBCdXQgbm90IGFzIGJvcmluZyBhcyB3YXRjaGluZyApIFRqDQpFVA0KQlQNCi9GMSAwMDEwIFRmDQo2OS4yNTAwIDY1Mi43NTIwIFRkDQooIHBhaW50IGRyeS4gQW5kIG1vcmUgdGV4dC4gQW5kIG1vcmUgdGV4dC4gQW5kIG1vcmUgdGV4dC4gQW5kIG1vcmUgdGV4dC4gKSBUag0KRVQNCkJUDQovRjEgMDAxMCBUZg0KNjkuMjUwMCA2NDAuODAwMCBUZA0KKCBCb3JpbmcuICBNb3JlLCBhIGxpdHRsZSBtb3JlIHRleHQuIFRoZSBlbmQsIGFuZCBqdXN0IGFzIHdlbGwuICkgVGoNCkVUDQplbmRzdHJlYW0NCmVuZG9iag0KDQo4IDAgb2JqDQpbL1BERiAvVGV4dF0NCmVuZG9iag0KDQo5IDAgb2JqDQo8PA0KL1R5cGUgL0ZvbnQNCi9TdWJ0eXBlIC9UeXBlMQ0KL05hbWUgL0YxDQovQmFzZUZvbnQgL0hlbHZldGljYQ0KL0VuY29kaW5nIC9XaW5BbnNpRW5jb2RpbmcNCj4+DQplbmRvYmoNCg0KMTAgMCBvYmoNCjw8DQovQ3JlYXRvciAoUmF2ZSBcKGh0dHA6Ly93d3cubmV2cm9uYS5jb20vcmF2ZVwpKQ0KL1Byb2R1Y2VyIChOZXZyb25hIERlc2lnbnMpDQovQ3JlYXRpb25EYXRlIChEOjIwMDYwMzAxMDcyODI2KQ0KPj4NCmVuZG9iag0KDQp4cmVmDQowIDExDQowMDAwMDAwMDAwIDY1NTM1IGYNCjAwMDAwMDAwMTkgMDAwMDAgbg0KMDAwMDAwMDA5MyAwMDAwMCBuDQowMDAwMDAwMTQ3IDAwMDAwIG4NCjAwMDAwMDAyMjIgMDAwMDAgbg0KMDAwMDAwMDM5MCAwMDAwMCBuDQowMDAwMDAxNTIyIDAwMDAwIG4NCjAwMDAwMDE2OTAgMDAwMDAgbg0KMDAwMDAwMjQyMyAwMDAwMCBuDQowMDAwMDAyNDU2IDAwMDAwIG4NCjAwMDAwMDI1NzQgMDAwMDAgbg0KDQp0cmFpbGVyDQo8PA0KL1NpemUgMTENCi9Sb290IDEgMCBSDQovSW5mbyAxMCAwIFINCj4+DQoNCnN0YXJ0eHJlZg0KMjcxNA0KJSVFT0YNCg==', content_id='4D1548BC249BAE45BB9EE4649D5384BA@eurprd08.prod.outlook.com', content_location=None)]
```

The attachment file itself is a simple sample.pdf from https://www.africau.edu/images/default/sample.pdf

**Comment by jussihi** [comment]
I've upgraded the `kiota-abstractions` to 0.8.5 as you suggested in the last issue I had:

```
(.venv) [jussi@ graph-mail]$ pip show microsoft-kiota-abstractions
Name: microsoft-kiota-abstractions
Version: 0.8.5
Summary: Core abstractions for kiota generated libraries in Python
Home-page:
Author:
Author-email: Microsoft <graphtooling+python@microsoft.com>
License:
Location: /home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages
Requires: opentelemetry-api, opentelemetry-sdk, std-uritemplate
Required-by: microsoft-kiota-authentication-azure, microsoft-kiota-http, microsoft-kiota-serialization-json, microsoft-kiota-serialization-text, msgraph-core, msgraph-sdk
```

**Comment by samwelkanda** [comment]
@jussihi 
 
I'm unable to replicate the issue using the sample pdf you shared. 

Could it have been a network issue? 

Request:
```PY
# COPY ASSIGN ATTACHMENTS OF A SPECIFIC MESSAGE FOR A SPECIFIC USER
async def get_attachment():
    
    message = await client.users.by_user_id('USER-ID).messages.by_message_id(MSG-ID).get()
    if message:
        attachments =   await client.users.by_user_id('USER-ID).messages.by_message_id(message.id).attachments.get()
        if attachments and attachments.value:
            message.attachments = attachments.value
            print(message.attachments)
asyncio.run(get_attachment())
```

Output:
```cmd
[FileAttachment(additional_data={'@odata.mediaContentType': 'application/octet-stream'}, id='AAMkAGVhMzU.....yNdClKfj6lfL6yo=', odata_type='#microsoft.graph.fileAttachment', content_type='application/octet-stream', is_inline=False, last_modified_date_time=datetime.datetime(2023, 9, 17, 21, 49, 20, tzinfo=tzutc()), name='Sample PDF', size=3166, content_bytes=b'JVBERi0xLjMNCiXi4.....0YNCg==', content_id=None, content_location=None)]
```

**Comment by jussihi** [comment]
@samwelkanda 

I doubt it is a network issue. I can replicate it 100% of the time with my current setup. In my setup, my mailbox has other items too that process just well before getting stuck to this one. I will try to create a new mailbox instance and reproduce this hang with it. I will reply back if I'm able to do so.

**Comment by jussihi** [comment]
@samwelkanda Ok, I'm able to reproduce with these steps:

1. Create a new MS test tenant shared mailbox with initially 0 messages, assign e5 license
2. Send 3 mails to this box: 1st without attachment, 2nd with aforementioned sample.pdf and 3rd with a sample xml [1]
3. Run following simple snippet against this mailbox:

```python
async def process_single_mailbox(graph_client: GraphServiceClient) -> None:
    user_id = "test-mailbox@...onmicrosoft.com"
    try:
        new_messages = await (graph_client.users.by_user_id(user_id).mail_folders.by_mail_folder_id("inbox").messages.delta.get())
    except APIError as e:
        print(e.error.message)

    messages: Optional[List[Message]] = new_messages.value
    if messages is not None:
        for new_message in messages:
            try:
                attachments = (await (graph_client.users.by_user_id(user_id).messages.by_message_id(new_message.id).attachments.get())).value
                if attachments is None:
                    print("something weird happened, there should be an attachment list")
                new_message.attachments = attachments

            except APIError as e:
                print(e.error.message)
    return



async def main():
    # init GraphClient ...
    while True:
                await asyncio.gather(process_single_mailbox(graph_client), asyncio.sleep(1))
    
```

[1]: https://www.w3schools.com/xml/note.xml

**Comment by jussihi** [comment]
With the setup mentioned above, my code gets stuck at the 3rd message (the one without attachment!) because it traverses the inbox messages from latest to oldest. 

Last time it seemed to get stuck to the 3rd message too, it went through the first 2 messages just fine but got stuck to 3rd (out of 5 messages in inbox). That time it just happened to be the sample.pdf inside the 3rd message. Now the 3rd message doesn't have an attachment but the program still hangs for some reason

**Comment by jussihi** [comment]
![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/25184163/07cd00d4-18a7-46a7-b2e6-83751d9ccba2)

The python process seems to get stuck to an endless loop (100% CPU usage on a single core). It also seems to be continuously allocating more and more memory to the program instance while stuck, see htop screenshot attached. At some point the program gets killed (I guess by Linux oomkiller)

**Comment by jussihi** [comment]
The snippet seems to repeatedly call `in_memory_backing_store`'s `_ensure_collection_size_is_consistent` from its `is_initialization_completed`

Here is another output after the attachment list copy assignment
```
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/backed_model.py", line 31, in __setattr__
    self.backing_store.set(prop, val)
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 112, in set
    self.__subscriptions[sub](key, old_value, value_to_add)
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 107, in <lambda>
    lambda prop_key, old_val, new_val: self.set(key, value)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 105, in set
    item.backing_store.is_initialization_completed = True
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 38, in is_initialization_completed
    self._ensure_collection_size_is_consistent(key, val[1])
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 198, in _ensure_collection_size_is_consistent
    self.set(key, entry[0])  # dirty track the change
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 112, in set
    self.__subscriptions[sub](key, old_value, value_to_add)
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 107, in <lambda>
    lambda prop_key, old_val, new_val: self.set(key, value)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 105, in set
    item.backing_store.is_initialization_completed = True
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 38, in is_initialization_completed
    self._ensure_collection_size_is_consistent(key, val[1])
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 198, in _ensure_collection_size_is_consistent
    self.set(key, entry[0])  # dirty track the change
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 112, in set
    self.__subscriptions[sub](key, old_value, value_to_add)
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 107, in <lambda>
    lambda prop_key, old_val, new_val: self.set(key, value)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 105, in set
    item.backing_store.is_initialization_completed = True
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 37, in is_initialization_completed
    val[1].backing_store.is_initialization_completed = value
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 38, in is_initialization_completed
    self._ensure_collection_size_is_consistent(key, val[1])
  File "/home/jussi/testi/graph-mail/.venv/lib/python3.11/site-packages/kiota_abstractions/store/in_memory_backing_store.py", line 178, in _ensure_collection_size_is_consistent
    print("here")
  File "/usr/lib/python3.11/asyncio/runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt
```

**Comment by jussihi** [comment]
@samwelkanda 

Are you able to reproduce this issue with given steps or do you need a more generalized example?

**Comment by jussihi** [comment]
Debugging the issue, I can see that the trace is follows:

```
set (\home\jussi\testi\graph-mail\.venv\lib\python3.11\site-packages\kiota_abstractions\store\in_memory_backing_store.py:106)
<lambda> (\home\jussi\testi\graph-mail\.venv\lib\python3.11\site-packages\kiota_abstractions\store\in_memory_backing_store.py:107)
set (\home\jussi\testi\graph-mail\.venv\lib\python3.11\site-packages\kiota_abstractions\store\in_memory_backing_store.py:112)
_ensure_collection_size_is_consistent (\home\jussi\testi\graph-mail\.venv\lib\python3.11\site-packages\kiota_abstractions\store\in_memory_backing_store.py:196)
is_initialization_completed (\home\jussi\testi\graph-mail\.venv\lib\python3.11\site-packages\kiota_abstractions\store\in_memory_backing_store.py:38)
set (\home\jussi\testi\graph-mail\.venv\lib\python3.11\site-packages\kiota_abstractions\store\in_memory_backing_store.py:105)
<lambda> (\home\jussi\testi\graph-mail\.venv\lib\python3.11\site-packages\kiota_abstractions\store\in_memory_backing_store.py:107)
set (\home\jussi\testi\graph-mail\.venv\lib\python3.11\site-packages\kiota_abstractions\store\in_memory_backing_store.py:112)
_ensure_collection_size_is_consistent (\home\jussi\testi\graph-mail\.venv\lib\python3.11\site-packages\kiota_abstractions\store\in_memory_backing_store.py:196)
is_initialization_completed (\home\jussi\testi\graph-mail\.venv\lib\python3.11\site-packages\kiota_abstractions\store\in_memory_backing_store.py:38)
set (\home\jussi\testi\graph-mail\.venv\lib\python3.11\site-packages\kiota_abstractions\store\in_memory_backing_store.py:105)
<lambda> (\home\jussi\testi\graph-mail\.venv\lib\python3.11\site-packages\kiota_abstractions\store\in_memory_backing_store.py:107)
set (\home\jussi\testi\graph-mail\.venv\lib\python3.11\site-packages\kiota_abstractions\store\in_memory_backing_store.py:112)
__setattr__ (\home\jussi\testi\graph-mail\.venv\lib\python3.11\site-packages\kiota_abstractions\store\backed_model.py:31)
process_single_mailbox (\home\jussi\testi\graph-mail\test.py:59)
_run (\usr\lib\python3.11\asyncio\events.py:80)
_run_once (\usr\lib\python3.11\asyncio\base_events.py:1914)
run_forever (\usr\lib\python3.11\asyncio\base_events.py:607)
run_until_complete (\usr\lib\python3.11\asyncio\base_events.py:640)
run (\usr\lib\python3.11\asyncio\runners.py:118)
run (\usr\lib\python3.11\asyncio\runners.py:190)
<module> (\home\jussi\testi\graph-mail\main.py:43)
_run_code (\usr\lib\python3.11\runpy.py:88)
_run_module_as_main (\usr\lib\python3.11\runpy.py:198)
```

When I add a breakpoint to a uuid generator, the recurring call stack can be found from the top of the last call stack:

```
__init__ (\usr\lib\python3.11\uuid.py:139)
uuid4 (\usr\lib\python3.11\uuid.py:723)
subscribe (\home\jussi\testi\graph-mail\.venv\lib\python3.11\site-packages\kiota_abstractions\store\in_memory_backing_store.py:160)
set (\home\jussi\testi\graph-mail\.venv\lib\python3.11\site-packages\kiota_abstractions\store\in_memory_backing_store.py:106)
<lambda> (\home\jussi\testi\graph-mail\.venv\lib\python3.11\site-packages\kiota_abstractions\store\in_memory_backing_store.py:107)
set (\home\jussi\testi\graph-mail\.venv\lib\python3.11\site-packages\kiota_abstractions\store\in_memory_backing_store.py:112)
```

In other words, the code ~~never returns~~ takes very long time to return from `in_memory_backing_sore.py`'s `_ensure_collection_size_is_consistent`'s call to dirty track the change (on my `kiota_abstractions`, line 196), the code is
```python
            if len(entry[0]) != entry[1]:  # if the size has changed since last update
                self.set(key, entry[0])  # dirty track the change <-- Gets stuck here for a very long time, takes almost a minute to return, 
```

**Comment by samwelkanda** [comment]
Thanks for the detailed information @jussihi 

I am looking into it and will provide feedback shortly

**Comment by samwelkanda** [comment]
Hi @jussihi 

Unfortunately I am still not able to replicate this error.

Looking at the code you shared:
```py
async def main():
    # init GraphClient ...
    while True:
                await asyncio.gather(process_single_mailbox(graph_client), asyncio.sleep(1))
```
Is there a condition that breaks the while loop?

**Comment by jussihi** [comment]
@samwelkanda 

No, there is not, I want to periodically check for new messages so that I can always get the new, unprocessed messages. Am I doing it wrong?

EDIT: I'm using the `delta` method to get the message delta (but not using the delta key/id whatever for now in message headers, so I keep getting all the messages all the time)

The problem is that even if there was not a loop, the program would still hang.

**Comment by jussihi** [comment]
Hmm. I will try the same code tomorrow with a native linux installation instead of running it inside WSL2. I just can't understand what I'm doing wrong

**Comment by jussihi** [comment]
I've now tested my code on native Linux (Arch) running python 3.11.3, WSL2 Arch Linux running python 3.11.5 and WSL2 Ubuntu running python 3.10.12. My code hangs on all of these three variants. I'm beginning to believe that there is something wrong with my code, it just is hard to find out what it is. Next I will try to run the same code but with no delta change but simply retrieving all messages. Let's see if it would help at all :)

**Comment by jussihi** [comment]
When I add 

```python
request_configuration = DeltaRequestBuilder.DeltaRequestBuilderGetRequestConfiguration(
    headers = {
        'Prefer' : "odata.maxpagesize=1",
    }
)
```

To the request configuration of the message request, I no longer have the issue. So I think I will just use it this way for time being :)
