### ISSUE TITLE
Unable to retrieve access review definitions from identity_governance

### ISSUE THREAD

**Issue by masyanru** [microsoftgraph/msgraph-sdk-python#385]
```
scopes = ['https://graph.microsoft.com/.default']
auth_provider = AzureIdentityAuthenticationProvider(credential, scopes=scopes)
request_adapter = GraphRequestAdapter(auth_provider)
client = GraphServiceClient(request_adapter=request_adapter)

query_params = DefinitionsRequestBuilder.DefinitionsRequestBuilderGetQueryParameters(
    top=20,
    skip=0,
)

request_configuration = DefinitionsRequestBuilder.DefinitionsRequestBuilderGetRequestConfiguration(
    query_parameters=query_params,

)
result = asyncio.run(client.identity_governance.access_reviews.definitions.get(request_configuration=request_configuration))
```

and `result` returns `dateutil.parser._parser.ParserError: Unknown string format: P30D`

if I change `top=10` or `top=19` (yeah, it's weird) it works fine and I get access review definitions from response.

```
/Users/masyan/ops/rbac-review/.venv/bin/python /Users/masyan/ops/rbac-review/pre-main.py 
Traceback (most recent call last):
  File "/Users/masyan/ops/rbac-review/pre-main.py", line 37, in <module>
    result = asyncio.run(client.identity_governance.access_reviews.definitions.get(request_configuration=request_configuration))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/masyan/ops/rbac-review/.venv/lib/python3.11/site-packages/msgraph/generated/identity_governance/access_reviews/definitions/definitions_request_builder.py", line 79, in get
    return await self.request_adapter.send_async(request_info, AccessReviewScheduleDefinitionCollectionResponse, error_mapping)

  File "/Users/masyan/ops/rbac-review/.venv/lib/python3.11/site-packages/kiota_http/httpx_request_adapter.py", line 178, in send_async
    value = root_node.get_object_value(parsable_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masyan/ops/rbac-review/.venv/lib/python3.11/site-packages/kiota_serialization_json/json_parse_node.py", line 209, in get_object_value
    self._assign_field_values(result)
  File "/Users/masyan/ops/rbac-review/.venv/lib/python3.11/site-packages/kiota_serialization_json/json_parse_node.py", line 278, in _assign_field_values
    field_deserializer(JsonParseNode(field_value))
  File "/Users/masyan/ops/rbac-review/.venv/lib/python3.11/site-packages/msgraph/generated/models/access_review_schedule_definition_collection_response.py", line 40, in <lambda>
    "value": lambda n : setattr(self, 'value', n.get_collection_of_object_values(AccessReviewScheduleDefinition)),
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masyan/ops/rbac-review/.venv/lib/python3.11/site-packages/kiota_serialization_json/json_parse_node.py", line 160, in get_collection_of_object_values
    return list(
           ^^^^^
  File "/Users/masyan/ops/rbac-review/.venv/lib/python3.11/site-packages/kiota_serialization_json/json_parse_node.py", line 162, in <lambda>
    lambda x: self._create_new_node(x).get_object_value(factory),  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masyan/ops/rbac-review/.venv/lib/python3.11/site-packages/kiota_serialization_json/json_parse_node.py", line 209, in get_object_value
    self._assign_field_values(result)
  File "/Users/masyan/ops/rbac-review/.venv/lib/python3.11/site-packages/kiota_serialization_json/json_parse_node.py", line 278, in _assign_field_values
    field_deserializer(JsonParseNode(field_value))
  File "/Users/masyan/ops/rbac-review/.venv/lib/python3.11/site-packages/msgraph/generated/models/access_review_schedule_definition.py", line 101, in <lambda>
    "settings": lambda n : setattr(self, 'settings', n.get_object_value(AccessReviewScheduleSettings)),
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masyan/ops/rbac-review/.venv/lib/python3.11/site-packages/kiota_serialization_json/json_parse_node.py", line 209, in get_object_value
    self._assign_field_values(result)
  File "/Users/masyan/ops/rbac-review/.venv/lib/python3.11/site-packages/kiota_serialization_json/json_parse_node.py", line 278, in _assign_field_values
    field_deserializer(JsonParseNode(field_value))
  File "/Users/masyan/ops/rbac-review/.venv/lib/python3.11/site-packages/msgraph/generated/models/access_review_schedule_settings.py", line 84, in <lambda>
    "recommendationLookBackDuration": lambda n : setattr(self, 'recommendation_look_back_duration', n.get_timedelta_value()),
                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masyan/ops/rbac-review/.venv/lib/python3.11/site-packages/kiota_serialization_json/json_parse_node.py", line 104, in get_timedelta_value
    datetime_obj = parser.parse(self._json_node)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masyan/ops/rbac-review/.venv/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masyan/ops/rbac-review/.venv/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: P30D

Process finished with exit code 1
```

**Comment by melkikh** [comment]
I have same issues too

**Comment by samwelkanda** [comment]
@masyanru 

Thanks for reporting this issue. This was caused by the `dateutil` dependency being unable to parse the datetime format of the response. We recently switched to a library that supports more datetime types. 

Please update to the latest stable version of the SDK(v1.0.0) to resolve.

Thanks.
cc @melkikh

**Comment by draew6** [comment]
@samwelkanda I received
    raise ParserError("Unable to parse string [{}]".format(text))
pendulum.parsing.exceptions.ParserError: Unable to parse string [-PT1H15M]

when creating appointment. Is it same issue? I am on latest
