### ISSUE TITLE
msgraph.generated.models.o_data_errors.o_data_error.ODataError while listing emails

### ISSUE THREAD

**Issue by dwinsi** [microsoftgraph/msgraph-sdk-python#49]
I am getting error "msgraph.generated.models.o_data_errors.o_data_error.ODataError" 

graph.py

```
from configparser import SectionProxy
from azure.identity.aio import ClientSecretCredential
from kiota_authentication_azure.azure_identity_authentication_provider import (AzureIdentityAuthenticationProvider)
from msgraph import GraphRequestAdapter, GraphServiceClient
from msgraph.generated.me.messages.messages_request_builder import MessagesRequestBuilder
from msgraph.generated.users.users_request_builder import UsersRequestBuilder
class Graph:
    settings: SectionProxy
    client_credential: ClientSecretCredential
    adapter: GraphRequestAdapter
    app_client: GraphServiceClient

   def __init__(self, config: SectionProxy):
        self.settings = config
        client_id = self.settings['clientId']
        tenant_id = self.settings['tenantId']
        client_secret = self.settings['clientSecret']

        self.client_credential = ClientSecretCredential(tenant_id, client_id, client_secret)
        auth_provider = AzureIdentityAuthenticationProvider(self.client_credential)  # type: ignore
        self.adapter = GraphRequestAdapter(auth_provider)
        self.app_client = GraphServiceClient(self.adapter)

    async def get_inbox(self):
        query_params = MessagesRequestBuilder.MessagesRequestBuilderGetQueryParameters(
            # Only request specific properties
            select=['from', 'isRead', 'receivedDateTime', 'subject'],
            # Get at most 25 results
            top=25,
            # Sort by received time, newest first
            orderby=['receivedDateTime DESC']
        )
        request_config = MessagesRequestBuilder.MessagesRequestBuilderGetRequestConfiguration(
            query_parameters=query_params
        )

        messages = await self.app_client.me()\
            .mail_folders_by_id('inbox')\
            .messages()\
            .get(request_configuration=request_config)
        return messages
```

main.py

```
import asyncio
import configparser
from graph import Graph


async def main():
    print('Python Graph App-Only Tutorial\n')

    # Load settings
    config = configparser.ConfigParser()
    config.read(['config.cfg', 'config.dev.cfg'])
    azure_settings = config['azure']

    graph: Graph = Graph(azure_settings)

async def list_inbox(graph: Graph):
    message_page = await graph.get_inbox()
    if message_page is not None and message_page.value is not None:
        # Output each message's details
        for message in message_page.value:
            print('Message:', message.subject)
            if (
                message.from_escaped is not None and
                message.from_escaped.email_address is not None
            ):
                print('  From:', message.from_escaped.email_address.name or 'NONE')
            else:
                print('  From: NONE')
            print('  Status:', 'Read' if message.is_read else 'Unread')
            print('  Received:', message.received_date_time)

        # If @odata.nextLink is present
        more_available = message_page.odata_next_link is not None
        print('\nMore messages available?', more_available, '\n')
```

Error:

`
Traceback (most recent call last):
  File "C:\Users\xxx\PycharmProjects\MSGraph_App_Only\main.py", line 121, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\xxxx\PycharmProjects\MSGraph_App_Only\main.py", line 43, in main
    await list_inbox(graph)
  File "C:\Users\xxxxx\PycharmProjects\MSGraph_App_Only\main.py", line 80, in list_inbox
    message_page = await graph.get_inbox()
  File "C:\Users\xxxxxx\PycharmProjects\MSGraph_App_Only\graph.py", line 67, in get_inbox
    messages = await self.app_client.me()\
  File "C:\Users\xxxxxx\PycharmProjects\MSGraph_App_Only\venv\lib\site-packages\msgraph\generated\me\mail_folders\item\messages\messages_request_builder.py", line 110, in get
    return await self.request_adapter.send_async(request_info, message_collection_response.MessageCollectionResponse, response_handler, error_mapping)
  File "C:\Users\xxxxxx\PycharmProjects\MSGraph_App_Only\venv\lib\site-packages\kiota_http\httpx_request_adapter.py", line 119, in send_async
    await self.throw_failed_responses(response, error_map)
  File "C:\Users\xxxxx\PycharmProjects\MSGraph_App_Only\venv\lib\site-packages\kiota_http\httpx_request_adapter.py", line 316, in throw_failed_responses
    raise error
msgraph.generated.models.o_data_errors.o_data_error.ODataError
`

**Comment by dwinsi** [comment]
Below line has issue:
```
messages = await self.app_client.me()\
            .mail_folders_by_id('inbox')\
            .messages()\
            .get(request_configuration=request_config)
```

Changed it to 

```
messages = await self.app_client.users_by_id(UPN)\
            .mail_folders_by_id('inbox')\
            .messages()\
            .get(request_configuration=request_config)
```

and it got fixed.
