### ISSUE TITLE
Get synchronizationSchema crashes

### ISSUE THREAD

**Issue by pauliusmiskinis** [microsoftgraph/msgraph-sdk-python#625]
Test code, using `msgraph-sdk v1.1.0`:
```
import asyncio
from azure.identity.aio import ClientSecretCredential
from msgraph import GraphServiceClient

sp_id = "<REMOVED>"
sync_job_id = "aWSSingleSignon.<REMOVED>"

credentials = ClientSecretCredential(<REMOVED>, <REMOVED>, <REMOVED>)
client = GraphServiceClient(credentials=credentials)

async def main():
    schema = await client.service_principals.by_service_principal_id(sp_id).synchronization.jobs.by_synchronization_job_id(sync_job_id).schema.get()

asyncio.run(main())
```

This is what you get:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 199, in get_enum_value
    return enum_class[camel_case_key]  # type: ignore
  File "/usr/lib64/python3.8/enum.py", line 387, in __getitem__
    return cls._member_map_[name]
KeyError: 'Secret'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 19, in <module>
    asyncio.run(main())
  File "/usr/lib64/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "example.py", line 17, in main
    schema = await client.service_principals.by_service_principal_id(sp_id).synchronization.jobs.by_synchronization_job_id(sync_job_id).schema.get()
  File "/usr/local/lib/python3.8/site-packages/msgraph/generated/service_principals/item/synchronization/jobs/item/schema/schema_request_builder.py", line 72, in get
    return await self.request_adapter.send_async(request_info, SynchronizationSchema, error_mapping)
  File "/usr/local/lib/python3.8/site-packages/kiota_http/httpx_request_adapter.py", line 192, in send_async
    value = root_node.get_object_value(parsable_factory)
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 212, in get_object_value
    self._assign_field_values(result)
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 281, in _assign_field_values
    field_deserializer(JsonParseNode(field_value))
  File "/usr/local/lib/python3.8/site-packages/msgraph/generated/models/synchronization_schema.py", line 49, in <lambda>
    "directories": lambda n : setattr(self, 'directories', n.get_collection_of_object_values(DirectoryDefinition)),
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 163, in get_collection_of_object_values
    return list(
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 165, in <lambda>
    lambda x: self._create_new_node(x).get_object_value(factory),  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 212, in get_object_value
    self._assign_field_values(result)
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 281, in _assign_field_values
    field_deserializer(JsonParseNode(field_value))
  File "/usr/local/lib/python3.8/site-packages/msgraph/generated/models/directory_definition.py", line 59, in <lambda>
    "objects": lambda n : setattr(self, 'objects', n.get_collection_of_object_values(ObjectDefinition)),
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 163, in get_collection_of_object_values
    return list(
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 165, in <lambda>
    lambda x: self._create_new_node(x).get_object_value(factory),  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 212, in get_object_value
    self._assign_field_values(result)
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 281, in _assign_field_values
    field_deserializer(JsonParseNode(field_value))
  File "/usr/local/lib/python3.8/site-packages/msgraph/generated/models/object_definition.py", line 52, in <lambda>
    "attributes": lambda n : setattr(self, 'attributes', n.get_collection_of_object_values(AttributeDefinition)),
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 163, in get_collection_of_object_values
    return list(
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 165, in <lambda>
    lambda x: self._create_new_node(x).get_object_value(factory),  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 212, in get_object_value
    self._assign_field_values(result)
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 281, in _assign_field_values
    field_deserializer(JsonParseNode(field_value))
  File "/usr/local/lib/python3.8/site-packages/msgraph/generated/models/attribute_definition.py", line 82, in <lambda>
    "metadata": lambda n : setattr(self, 'metadata', n.get_collection_of_object_values(AttributeDefinitionMetadataEntry)),
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 163, in get_collection_of_object_values
    return list(
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 165, in <lambda>
    lambda x: self._create_new_node(x).get_object_value(factory),  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 212, in get_object_value
    self._assign_field_values(result)
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 281, in _assign_field_values
    field_deserializer(JsonParseNode(field_value))
  File "/usr/local/lib/python3.8/site-packages/msgraph/generated/models/attribute_definition_metadata_entry.py", line 45, in <lambda>
    "key": lambda n : setattr(self, 'key', n.get_enum_value(AttributeDefinitionMetadata)),
  File "/usr/local/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 201, in get_enum_value
    raise Exception(f'Invalid key: {camel_case_key} for enum {enum_class}.')
Exception: Invalid key: Secret for enum <enum 'AttributeDefinitionMetadata'>.
```

Same call via HTTP works fine.

**Comment by andrueastman** [comment]
Possibly related to enum work at https://github.com/microsoft/kiota-serialization-json-python/pull/265

**Comment by pauliusmiskinis** [comment]
Confirmed working with v1.3.0 👍
