### ISSUE TITLE
Bug: TypeError when creating an external connection with a layout

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/msgraph-sdk-python#670]
When trying to create an external connection with a custom layout, the Python SDK throws the following error:

```text
$ python3 main.py create-connection
Traceback (most recent call last):
  File "~/pnp/graph-connectors-samples/samples/python-markdown/main.py", line 7, in <module>
    asyncio.run(create_connection())
  File "~/.pyenv/versions/3.11.5/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/3.11.5/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/3.11.5/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "~/pnp/graph-connectors-samples/samples/python-markdown/connection_service.py", line 41, in create_connection
    await _create_connection()
  File "~/pnp/graph-connectors-samples/samples/python-markdown/connection_service.py", line 25, in _create_connection
    await graph_client.external.connections.post(external_connection)
  File "~/pnp/graph-connectors-samples/samples/python-markdown/venv/lib/python3.11/site-packages/msgraph/generated/external/connections/connections_request_builder.py", line 77, in post
    request_info = self.to_post_request_information(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/pnp/graph-connectors-samples/samples/python-markdown/venv/lib/python3.11/site-packages/msgraph/generated/external/connections/connections_request_builder.py", line 114, in to_post_request_information
    request_info.set_content_from_parsable(self.request_adapter, "application/json", body)
  File "~/pnp/graph-connectors-samples/samples/python-markdown/venv/lib/python3.11/site-packages/kiota_abstractions/request_information.py", line 179, in set_content_from_parsable
    writer.write_object_value(None, values)
  File "~/pnp/graph-connectors-samples/samples/python-markdown/venv/lib/python3.11/site-packages/kiota_serialization_json/json_serialization_writer.py", line 285, in write_object_value
    self._serialize_value(temp_writer, value)
  File "~/pnp/graph-connectors-samples/samples/python-markdown/venv/lib/python3.11/site-packages/kiota_serialization_json/json_serialization_writer.py", line 462, in _serialize_value
    value.serialize(temp_writer)
  File "~/pnp/graph-connectors-samples/samples/python-markdown/venv/lib/python3.11/site-packages/msgraph/generated/models/external_connectors/external_connection.py", line 117, in serialize
    writer.write_object_value("searchSettings", self.search_settings)
  File "~/pnp/graph-connectors-samples/samples/python-markdown/venv/lib/python3.11/site-packages/kiota_serialization_json/json_serialization_writer.py", line 285, in write_object_value
    self._serialize_value(temp_writer, value)
  File "~/pnp/graph-connectors-samples/samples/python-markdown/venv/lib/python3.11/site-packages/kiota_serialization_json/json_serialization_writer.py", line 462, in _serialize_value
    value.serialize(temp_writer)
  File "~/pnp/graph-connectors-samples/samples/python-markdown/venv/lib/python3.11/site-packages/msgraph/generated/models/external_connectors/search_settings.py", line 57, in serialize
    writer.write_collection_of_object_values("searchResultTemplates", self.search_result_templates)
  File "~/pnp/graph-connectors-samples/samples/python-markdown/venv/lib/python3.11/site-packages/kiota_serialization_json/json_serialization_writer.py", line 228, in write_collection_of_object_values
    temp_writer.write_object_value(None, val)
  File "~/pnp/graph-connectors-samples/samples/python-markdown/venv/lib/python3.11/site-packages/kiota_serialization_json/json_serialization_writer.py", line 285, in write_object_value
    self._serialize_value(temp_writer, value)
  File "~/pnp/graph-connectors-samples/samples/python-markdown/venv/lib/python3.11/site-packages/kiota_serialization_json/json_serialization_writer.py", line 462, in _serialize_value
    value.serialize(temp_writer)
  File "~/pnp/graph-connectors-samples/samples/python-markdown/venv/lib/python3.11/site-packages/msgraph/generated/models/external_connectors/display_template.py", line 69, in serialize
    writer.write_object_value("layout", self.layout)
  File "~/pnp/graph-connectors-samples/samples/python-markdown/venv/lib/python3.11/site-packages/kiota_serialization_json/json_serialization_writer.py", line 285, in write_object_value
    self._serialize_value(temp_writer, value)
  File "~/pnp/graph-connectors-samples/samples/python-markdown/venv/lib/python3.11/site-packages/kiota_serialization_json/json_serialization_writer.py", line 462, in _serialize_value
    value.serialize(temp_writer)
  File "~/pnp/graph-connectors-samples/samples/python-markdown/venv/lib/python3.11/site-packages/msgraph/generated/models/json.py", line 47, in serialize
    writer.write_additional_data_value(self.additional_data)
  File "~/pnp/graph-connectors-samples/samples/python-markdown/venv/lib/python3.11/site-packages/kiota_serialization_json/json_serialization_writer.py", line 330, in write_additional_data_value
    self.write_any_value(key, val)
  File "~/pnp/graph-connectors-samples/samples/python-markdown/venv/lib/python3.11/site-packages/kiota_serialization_json/json_serialization_writer.py", line 444, in write_any_value
    raise TypeError(
TypeError: Encountered an unknown collection type during serialization                     <class 'list'> with key body
(venv)
```

The exact same code worked just fine with the preview version of the SDK.

### Packages

```text
microsoft-kiota-abstractions==1.3.2
microsoft-kiota-authentication-azure==1.0.0
microsoft-kiota-http==1.3.1
microsoft-kiota-serialization-form==0.1.0
microsoft-kiota-serialization-json==1.2.0
microsoft-kiota-serialization-multipart==0.1.0
microsoft-kiota-serialization-text==1.0.0
msgraph-core==1.0.0
msgraph-sdk==1.2.0
```

### Repro

- get this sample: https://github.com/pnp/graph-connectors-samples/tree/main/samples/python-markdown
- upgrade to the Graph Python SDK v1
- follow Minimal Path to Awesome steps from the readme
- run `python3 main.py create-connection` > error

**Comment by shemogumbe** [comment]
Hello, thanks for usIng the SDK and for raising this.
This seems to be related to graph connectors that to the SDK.
https://learn.microsoft.com/en-us/microsoftsearch/staged-rollout-for-graph-connectors
https://learn.microsoft.com/en-us/microsoftsearch/connectors-overview

**Comment by waldekmastykarz** [comment]
Why do you say it's not related to the SDK? I'm using the Graph SDK to create an external connection and the SDK is failing. I can perform the same operation using the REST API just fine. To me, this indicates that it's an SDK failure.
