### ISSUE TITLE
Unable to parse claims from response

### ISSUE THREAD

**Issue by shemogumbe** [microsoftgraph/msgraph-sdk-python#676]
**Is your feature request related to a problem? Please describe.**
This is a bug, it seems to apply when an async request using httpx_request adapter async client does not have proper authorization headers, and no token presented

**Describe the solution you'd like**
Requests work without a hack to get the token within the request body

**Describe alternatives you've considered**
Manually adding Auth information in the request information before sending the request,
`python
 access_token = "<your -token>"
 info.headers.try_add("Authorization", f"Bearer {access_token}")
` 

**Additional context**
The Error traceback looks like
`
Traceback (most recent call last):
  File "C:\Users\shemogumbe\kiota-python\msgraph-sdk-python-core\src\app_lfu2.py", line 111, in <module>
    asyncio.run(upload_large_file())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\shemogumbe\kiota-python\msgraph-sdk-python-core\src\app_lfu2.py", line 102, in upload_large_file
    upload_result = await task.upload(progress_callback)
  File "C:\Users\shemogumbe\kiota-python\msgraph-sdk-python-core\src\msgraph_core\tasks\large_file_upload.py", line 116, in upload
    session = await self.next_chunk(
  File "C:\Users\shemogumbe\kiota-python\msgraph-sdk-python-core\src\msgraph_core\tasks\large_file_upload.py", line 194, in next_chunk
    return await self.request_adapter.send_async(info, parsable_factory, error_map)
  File "C:\Users\shemogumbe\kiota-python\msgraph-sdk-python-core\python_core_env\lib\site-packages\kiota_http\httpx_request_adapter.py", line 178, in send_async
    response = await self.get_http_response_message(request_info, parent_span)
  File "C:\Users\shemogumbe\kiota-python\msgraph-sdk-python-core\python_core_env\lib\site-packages\kiota_http\httpx_request_adapter.py", line 543, in get_http_response_message
    return await self.retry_cae_response_if_required(resp, request_info, claims)
  File "C:\Users\shemogumbe\kiota-python\msgraph-sdk-python-core\python_core_env\lib\site-packages\kiota_http\httpx_request_adapter.py", line 560, in retry_cae_response_if_required
    raise ValueError("Unable to parse claims from response")
ValueError: Unable to parse claims from response
`
and 
`
ValueError                                
Traceback (most recent call last)

      1 # GET /users?$top=500
      2 #users = await client.users.by_user_id('cjusko').get()
----> 3 users = await client.users.get()
      4 print(users.value)

File ~/.local/share/hatch/env/virtual/hat/hYHKRVU-/that/lib/python3.11/site-packages/msgraph/generated/users/users_request_builder.py:69, in UsersRequestBuilder.get(self, request_configuration)
     66     raise Exception("Http core is null") 
     67 from ..models.user_collection_response import UserCollectionResponse
---> 69 return await self.request_adapter.send_async(request_info, UserCollectionResponse, error_mapping)

File ~/.local/share/hatch/env/virtual/hat/hYHKRVU-/that/lib/python3.11/site-packages/kiota_http/httpx_request_adapter.py:178, in HttpxRequestAdapter.send_async(self, request_info, parsable_factory, error_map)
    175     parent_span.record_exception(REQUEST_IS_NULL)
    176     raise REQUEST_IS_NULL
--> 178 response = await self.get_http_response_message(request_info, parent_span)
    180 response_handler = self.get_response_handler(request_info)
    181 if response_handler:

File ~/.local/share/hatch/env/virtual/hat/hYHKRVU-/that/lib/python3.11/site-packages/kiota_http/httpx_request_adapter.py:543, in HttpxRequestAdapter.get_http_response_message(self, request_info, parent_span, claims)
    541     parent_span.set_attribute("http.response_content_type", content_type)
    542 _get_http_resp_span.end()
--> 543 return await self.retry_cae_response_if_required(resp, request_info, claims)

File ~/.local/share/hatch/env/virtual/that/hYHKRVU-/hat/lib/python3.11/site-packages/kiota_http/httpx_request_adapter.py:560, in HttpxRequestAdapter.retry_cae_response_if_required(self, resp, request_info, claims)
    558 claims_match = re.search('claims="(.+)"', auth_header_value)
    559 if not claims_match:
--> 560     raise ValueError("Unable to parse claims from response")
    561 response_claims = claims_match.group().split('="')[1]
    562 parent_span.add_event(AUTHENTICATE_CHALLENGED_EVENT_KEY)

ValueError: Unable to parse claims from response
`

**Comment by shemogumbe** [comment]
Related to https://github.com/microsoftgraph/msgraph-sdk-python/issues/672
