### ISSUE TITLE
Authentication failed: AADSTS65002

### ISSUE THREAD

**Issue by mplwork** [microsoftgraph/msgraph-sdk-python#677]
Trying this Python script from the Intro https://github.com/microsoftgraph/msgraph-sdk-python?tab=readme-ov-file#3-make-requests-against-the-service

```python
import asyncio
from azure.identity import InteractiveBrowserCredential
from msgraph import GraphServiceClient

credential = InteractiveBrowserCredential()
scopes=['User.Read']
client = GraphServiceClient(credentials=credential, scopes=scopes,)

# GET /me
async def me():
    me = await client.me.get()
    if me:
        print(me.display_name)
asyncio.run(me())
```

I get 
- a browser window where I can log in
- This error message:
```
py getme.py
InteractiveBrowserCredential.get_token failed: Authentication failed: AADSTS65002: Consent between first party application '04b07795
-8ddb-461a-bbee-02f9e1bf7b46' and first party resource '00000003-0000-0000-c000-000000000000' must be configured via preauthorizatio
n - applications owned and operated by Microsoft must get approval from the API owner before requesting tokens for that API. Trace I
D: 12a79ce6-72d0-45cf-bdcd-56b98d6c3400 Correlation ID: 55727982-91da-46eb-b961-ae813d04a01f Timestamp: 2024-04-22 12:12:14Z
Traceback (most recent call last):
  File "C:\MyStuff\NCygwin\home\me\O365\pyplan\getme.py", line 14, in <module>
    asyncio.run(me())
  File "C:\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\MyStuff\NCygwin\home\me\O365\pyplan\getme.py", line 11, in me
    me = await client.me.get()
         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\msgraph\generated\users\item\user_item_request_builder.py", line 158, in get
    return await self.request_adapter.send_async(request_info, User, error_mapping)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\kiota_http\httpx_request_adapter.py", line 178, in send_async
    response = await self.get_http_response_message(request_info, parent_span)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\kiota_http\httpx_request_adapter.py", line 523, in get_http_response_message
    await self._authentication_provider.authenticate_request(
  File "C:\Python311\Lib\site-packages\kiota_abstractions\authentication\base_bearer_token_authentication_provider.py", line 50, in
authenticate_request
    token = await self.access_token_provider.get_authorization_token(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\kiota_authentication_azure\azure_identity_access_token_provider.py", line 103, in get_authori
zation_token
    result = self._credentials.get_token(*self._scopes, claims=decoded_claim)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\azure\identity\_internal\interactive.py", line 173, in get_token
    raise ClientAuthenticationError(message=message, response=response)
azure.core.exceptions.ClientAuthenticationError: Authentication failed: AADSTS65002: Consent between first party application '04b077
95-8ddb-461a-bbee-02f9e1bf7b46' and first party resource '00000003-0000-0000-c000-000000000000' must be configured via preauthorizat
ion - applications owned and operated by Microsoft must get approval from the API owner before requesting tokens for that API. Trace
 ID: 12a79ce6-72d0-45cf-bdcd-56b98d6c3400 Correlation ID: 55727982-91da-46eb-b961-ae813d04a01f Timestamp: 2024-04-22 12:12:14Z

````

What am I missing?

**Comment by shemogumbe** [comment]
Hello, this should work fine
Check that:

1. You remembered to check the browser window and authenticate the request.
2. You can change the scopes to `['https://graph.microsoft.com/.default']`

We experienced a similar issue with [this ](https://github.com/microsoftgraph/msgraph-sdk-python/issues/544)
```python
credentials = InteractiveBrowserCredential()
scopes = ['https://graph.microsoft.com/.default']
auth_provider = AzureIdentityAuthenticationProvider(credentials)
user_client = GraphServiceClient(credentials=credentials, scopes=scopes)
print(user_client.request_adapter)
async def get_my_profile():
    try:
        me = await user_client.me.get()
        if me:
            print(f"User: {me.display_name} {me.id}")
    except APIError as e:
        print(f"Error: {e.error.code}: {e.error.message}")
asyncio.run(get_my_profile())
```
Confirm if this works, the scopes change

**Comment by mplwork** [comment]
Thanks for the reply. It turns out all that is required is to change the scopes:

> ```python
> credentials = InteractiveBrowserCredential()
> scopes = ['https://graph.microsoft.com/.default']
> ```
> 
> Confirm if this works, the scopes change

Yes it does. To sum it up this works:
 ```python
import asyncio
from azure.identity import InteractiveBrowserCredential
from msgraph import GraphServiceClient

credential = InteractiveBrowserCredential()
#scopes=['User.Read']

scopes = ['https://graph.microsoft.com/.default']

client = GraphServiceClient(credentials=credential, scopes=scopes,)

# GET /me
async def me():
    me = await client.me.get()
    if me:
        print(me.display_name)
asyncio.run(me())
```

**Comment by Sopka** [comment]
I had the same question. Thanks for the scopes hint!

This should be changed in the repository's README...

**Comment by shemogumbe** [comment]
The change has been effected in the Readme, Optionally, you can specify the client_id and the tenant_id in your credentials instantiation
```python
credential = InteractiveBrowserCredential(
    client_id="<your-client_id>",
    tenant_id="your-tenant-d"
)

scopes=['User.Read']
client = GraphServiceClient(credentials=credential, scopes=scopes,)
```
This is what we are updating in the readme
