### ISSUE TITLE
Multiple asyncio runs cause SSLWantReadError

### ISSUE THREAD

**Issue by Renji-FR** [microsoftgraph/msgraph-sdk-python#82]
Hi,

I would like to use the Microsoft graph SDK for Python with Django DB transaction.
As Django DB transaction `with transaction.atomic()` must be in sync context, I must use multiple `asyncio.run` calls.

> The question is how can we mix async graph requests and sync calls with multiple async calls?

The first `asyncio.run` works correctly, I am able to retrieve two `MailFolder` with their ID and messages in one of these folders.

```python
mailfolders = await asyncio.gather(
    self._retrieve_mailfolder_source(),
    self._retrieve_mailfolder_backup(),
    return_exceptions=False
)

# Same async event loop, no SSLWantReadError raised
result = await asyncio.gather(self._get_messages(mailfolders[0]))
```

The issue is for the second `asyncio.run`, the second call raise a `SSLWantReadError` exception.

For your information, when I run all graph requests in the same event loop, it works.
I don't know why with a second/different event loop, the graph request causes `SSLWantReadError` error.

It should be possible to execute many async calls with `asyncio.run`, correct?

```python
def _retrieve_mailfolders(self):
    mailfolders = await asyncio.gather(
        self._retrieve_mailfolder_source(),
        self._retrieve_mailfolder_backup(),
        return_exceptions=False
    )
    return mailfolders

def _retrieve(self):
    mailfolders = asyncio.run(self._retrieve_mailfolders())
    
    with transaction.atomic():
        # Second async run causes SSLWantReadError
        messages = asyncio.run(self._get_messages(mailfolders[0]))
```

## Exception

```
Scopes:
('https://graph.microsoft.com/.default',)

Token:
AccessToken(token='eyJ0eXAiOiJKV1QiLCJub25jZSI6Imo*********************************', expires_on=1675276095)

Successfully authenticated to Azure



Traceback (most recent call last):
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/anyio/streams/tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "/usr/lib/python3.10/ssl.py", line 917, in read
    v = self._sslobj.read(len)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2548)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/_async/http11.py", line 91, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/_async/http11.py", line 155, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/_async/http11.py", line 191, in _receive_event
    data = await self._network_stream.read(
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/anyio/streams/tls.py", line 195, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/anyio/streams/tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1264, in receive
    self._transport.resume_reading()
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 814, in resume_reading
    self._add_reader(self._sock_fd, self._read_ready)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 760, in _add_reader
    self._loop._add_reader(fd, callback, *args)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 253, in _add_reader
    self._check_closed()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/app_discover/core/adapters/emailMsGraph/msGraphAdapter.py", line 314, in _move_message
    message = await self._msgraph_client.me.messages_by_id(message.id).move.post(
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/msgraph/generated/me/messages/item/move/move_request_builder.py", line 58, in post
    return await self.request_adapter.send_async(request_info, message.Message, error_mapping)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/httpx_request_adapter.py", line 112, in send_async
    response = await self.get_http_response_message(request_info)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/httpx_request_adapter.py", line 320, in get_http_response_message
    resp = await self._http_client.send(request)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/msgraph_core/middleware/async_graph_transport.py", line 21, in handle_async_request
    response = await self.pipeline.send(request)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 31, in send
    return await self._first_middleware.send(request, self._transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/redirect_handler.py", line 65, in send
    response = await super().send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 57, in send
    return await self.next.send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/retry_handler.py", line 77, in send
    response = await super().send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 57, in send
    return await self.next.send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/parameters_name_decoding_handler.py", line 48, in send
    response = await super().send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 57, in send
    return await self.next.send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/msgraph_core/middleware/telemetry.py", line 48, in send
    response = await super().send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 54, in send
    response = await transport.handle_async_request(request)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/msgraph_core/middleware/async_graph_transport.py", line 21, in handle_async_request
    response = await self.pipeline.send(request)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 31, in send
    return await self._first_middleware.send(request, self._transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/redirect_handler.py", line 65, in send
    response = await super().send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 57, in send
    return await self.next.send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/retry_handler.py", line 77, in send
    response = await super().send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 57, in send
    return await self.next.send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/parameters_name_decoding_handler.py", line 48, in send
    response = await super().send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 57, in send
    return await self.next.send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/msgraph_core/middleware/telemetry.py", line 48, in send
    response = await super().send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 54, in send
    response = await transport.handle_async_request(request)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/_async/http11.py", line 111, in handle_async_request
    await self._response_closed()
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/_async/http11.py", line 224, in _response_closed
    await self.aclose()
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/_async/http11.py", line 232, in aclose
    await self._network_stream.aclose()
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 54, in aclose
    await self._stream.aclose()
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/anyio/streams/tls.py", line 192, in aclose
    await self.transport_stream.aclose()
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1323, in aclose
    self._transport.close()
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 706, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 753, in call_soon
    self._check_closed()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/manage.py", line 22, in <module>
    main()
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/app_discover/management/commands/discover.py", line 109, in handle
    raise e
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/app_discover/management/commands/discover.py", line 103, in handle
    messages = adapter.retrieve(store, range)
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/app_discover/core/adapters/emailMsGraph/msGraphAdapter.py", line 358, in retrieve
    raise e
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/app_discover/core/adapters/emailMsGraph/msGraphAdapter.py", line 355, in retrieve
    return self._retrieve(store, limit)
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/app_discover/core/adapters/emailMsGraph/msGraphAdapter.py", line 452, in _retrieve
    move, = asyncio.run(self._move_message(message, mailfolder_backup))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/app_discover/core/adapters/emailMsGraph/msGraphAdapter.py", line 321, in _move_message
    raise DiscoverAdapterError(
app_discover.errors.DiscoverAdapterError: Unable to move the message 'TCL TT: "*******" / "Emergency" / "Scheduled" / Planned Work Notification' to the mail folder 'Backup':
Event loop is closed
```

## Environment

Python version 3.10.9 (Ubuntu 20.04)

- azure-core :                                           1.26.2
- azure-identity :                                      1.12.0
- microsoft-kiota-abstractions :               0.3.0
- microsoft-kiota-authentication-azure : 0.2.0
- microsoft-kiota-http :                            0.3.1
- microsoft-kiota-serialization-json :       0.2.1
- microsoft-kiota-serialization-text :        0.2.0
- msgraph-core :                                      1.0.0a3
- msgraph-sdk :                                       1.0.0a9

**Comment by Renji-FR** [comment]
Got same error with Python 3.8, 3.9 and 3.10.

**Comment by samwelkanda** [comment]
Hi @Renji-FR 

Thank you for trying out our SDK!

Actually as per [asyncio docs](https://docs.python.org/3/library/asyncio-runner.html#id1)

> `asyncio.run` always creates a new event loop and closes it at the end. It should be used as a main entry point for asyncio programs, and should ideally only be called once.

For multiple calls, I would suggest getting the running event loop and using the loop to run the coroutine. i,e

```py
loop = asyncio.get_event_loop()
mailfolders = loop.run_until_complete(self._retrieve_mailfolders())
messages = loop.run_until_complete(self._get_messages(mailfolders[0]))
```

**Comment by Renji-FR** [comment]
Hi @samwelkanda

Thank you for your help.
I confirm your solution works as well.

I will close this issue and hope it can help someone else.

**Comment by Renji-FR** [comment]
The Python doc mention:
> Note In Python versions 3.10.0–3.10.8 and 3.11.0 this function (and other functions which use it implicitly) emitted a [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning) if there was no running event loop, even if the current loop was set on the policy. In Python versions 3.10.9, 3.11.1 and 3.12 they emit a [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning) if there is no running event loop and no current loop is set. In some future Python release this will become an error.

So maybe we can use:
```python
event_loop = asyncio.new_event_loop()
asyncio.set_event_loop(event_loop)

mailfolders = loop.run_until_complete(self._retrieve_mailfolders())
messages = loop.run_until_complete(self._get_messages(mailfolders[0]))

asyncio.set_event_loop(None)
event_loop.close()
```

But I don't know if `new_event_loop` will be deprecated too.

The question is why in async context and with a different event loop we got an SSL error, maybe something to configure in the `httpx` client?

**Comment by Renji-FR** [comment]
@samwelkanda Hi,

Now I have another exception related to asyncio when:
- 1 Open new event loop => OK
- 2 Run all Gaph requests with your SDK => OK
- 3 Close the event loop => OK
- 4 Wait X seconds (cron) => OK
- 5 Open new event loop => OK
- 6 Try to rerun the step `2` => KO

Are you sure you have not any issue with the async implementation? Because we can not use more than one time `asyncio.run(...)`, we can not rerun the same calls in a second event loop.

```
Traceback (most recent call last):
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/_synchronization.py", line 103, in wait
    await self._anyio_event.wait()
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1842, in wait
    if await self._event.wait():
  File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/_synchronization.py", line 102, in wait
    with anyio.fail_after(timeout):
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 234, in handle_async_request
    raise exc
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 227, in handle_async_request
    connection = await status.wait_for_connection(timeout=timeout)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 34, in wait_for_connection
    await self._connection_acquired.wait(timeout=timeout)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/_synchronization.py", line 101, in wait
    with map_exceptions(anyio_exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.PoolTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/manage.py", line 22, in <module>
    main()
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/app_discover/management/commands/discover.py", line 114, in handle
    raise e
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/app_discover/management/commands/discover.py", line 108, in handle
    messages = adapter.retrieve(store, range)
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/app_discover/core/adapters/emailMsGraph/msGraphAdapter.py", line 332, in retrieve
    raise e
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/app_discover/core/adapters/emailMsGraph/msGraphAdapter.py", line 329, in retrieve
    return self._retrieve(store, limit, event_loop)
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/app_discover/core/adapters/emailMsGraph/msGraphAdapter.py", line 344, in _retrieve
    mailfolder_source, mailfolder_backup = event_loop.run_until_complete(self._retrieve_mailfolders())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/app_discover/core/adapters/emailMsGraph/msGraphAdapter.py", line 316, in _retrieve_mailfolders
    mailfolders = await asyncio.gather(
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/app_discover/core/adapters/emailMsGraph/msGraphAdapter.py", line 282, in _retrieve_mailfolder_source
    mailfolder_source = await self._get_mailfolder(self._settings.mail_folder_search)
  File "/home/renji/scripts/f5/circuitMaintenanceParser/src/app_discover/core/adapters/emailMsGraph/msGraphAdapter.py", line 193, in _get_mailfolder
    folders:None|MessageCollectionResponse = await self._msgraph_client.me.mail_folders.get(
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/msgraph/generated/me/mail_folders/mail_folders_request_builder.py", line 71, in get
    return await self.request_adapter.send_async(request_info, mail_folder_collection_response.MailFolderCollectionResponse, error_mapping)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/httpx_request_adapter.py", line 112, in send_async
    response = await self.get_http_response_message(request_info)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/httpx_request_adapter.py", line 320, in get_http_response_message
    resp = await self._http_client.send(request)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/msgraph_core/middleware/async_graph_transport.py", line 21, in handle_async_request
    response = await self.pipeline.send(request)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 31, in send
    return await self._first_middleware.send(request, self._transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/redirect_handler.py", line 65, in send
    response = await super().send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 57, in send
    return await self.next.send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/retry_handler.py", line 77, in send
    response = await super().send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 57, in send
    return await self.next.send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/parameters_name_decoding_handler.py", line 48, in send
    response = await super().send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 57, in send
    return await self.next.send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/msgraph_core/middleware/telemetry.py", line 48, in send
    response = await super().send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 54, in send
    response = await transport.handle_async_request(request)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/msgraph_core/middleware/async_graph_transport.py", line 21, in handle_async_request
    response = await self.pipeline.send(request)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 31, in send
    return await self._first_middleware.send(request, self._transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/redirect_handler.py", line 65, in send
    response = await super().send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 57, in send
    return await self.next.send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/retry_handler.py", line 77, in send
    response = await super().send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 57, in send
    return await self.next.send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/parameters_name_decoding_handler.py", line 48, in send
    response = await super().send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 57, in send
    return await self.next.send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/msgraph_core/middleware/telemetry.py", line 48, in send
    response = await super().send(request, transport)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/kiota_http/middleware/middleware.py", line 54, in send
    response = await transport.handle_async_request(request)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/renji/virtualenvs/f5/maintenanceManager_3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.PoolTimeout
```

**Comment by agronholm** [comment]
AnyIO maintainer here. To support multiple successive calls to `asyncio.run()`, async code needs to drop any references to the old (closed) event loop, and this doesn't seem to be happening here. It seems it's trying to use the async resources (transport) created when the previous event loop was running, and that causes either timeouts or errors about the event loop being closed. The easiest solution is to run your entire app within a single event loop (i.e. `asyncio.run()`) call. Async is infectious like that :)

**Comment by Renji-FR** [comment]
@agronholm Thank you for your answer, I use Django and admin command so I can not run the entire app in sync.

For me the issue is in the MSGraph SDK that does not allow to have a loop for example (like a CRON) and call many time an async function to do a job using the MSGraph SDK.

**Comment by agronholm** [comment]
> I use Django and admin command so I can not run the entire app in sync.

So how about running the app asynchronously then? I believe modern releases of Django should support that.

> MSGraph SDK that does not allow to have a loop for example (like a CRON)

I didn't understand this. What do you mean by the SDK not allowing to have a loop?

**Comment by Renji-FR** [comment]
you said :
> To support multiple successive calls to asyncio.run(), async code needs to drop any references to the old (closed) event loop, and this doesn't seem to be happening here. It seems it's trying to use the async resources (transport) created when the previous event loop was running, and that causes either timeouts or errors about the event loop being closed.

This is my code, my entrypoint regarding my job:
```python
    def retrieve(self, store:Stores, limit:None|int) -> list[Messages]:
        try:
            event_loop = asyncio.new_event_loop()
            asyncio.set_event_loop(event_loop)
            
            return self._retrieve(store, limit, event_loop)
        except Exception as e:
            if self._logger.level <= logging.DEBUG:
                raise e
            else:
                if hasattr(e, 'error'):
                    e = e.error.message
                raise DiscoverAdapterError(str(e))
        finally:
            asyncio.set_event_loop(None)
            event_loop.close()
```
Then I use `event_loop.run_until_complete` to call async methods inside `_retrieve` sync method.
> retrieve (create event loop + close it) [sync] > _retrieve (job, retrieve mail folders, messages, ...) [sync] event_loop.run_until_complete(...) call async methods

So I close the event loop at the end, and don't keep any ref for the current job expect the provider `AzureIdentityAuthenticationProvider`, the adapter `GraphRequestAdapter` and the client `GraphServiceClient`.

If I want to call `retrieve` many times, every 1 minute for example, I got an error for the second call. Of course it works as well for the first call. My job is to retrieve emails for example, it is why I have a loop like a CRON.

Regarding Django and async functions, you talk about that https://docs.djangoproject.com/en/4.2/topics/async/#async-to-sync ? I am not sure I can use that and it can help me.

**Comment by sstoops** [comment]
I've [documented](https://github.com/microsoftgraph/msgraph-sdk-python/issues/366#issuecomment-1922252592) a bit of research and a new workaround I came up with in response to this issue over in #366 .

**Comment by shemogumbe** [comment]
While running multiple `asyncio.run` is an anti pattern and should avoided, you can find a hack here https://github.com/microsoftgraph/msgraph-sdk-python/discussions/683
