### ISSUE TITLE
Exception while fetching worksheet data

### ISSUE THREAD

**Issue by SamYuen101234** [microsoftgraph/msgraph-sdk-python#883]
### Describe the bug

I am trying to fetch data from sharepoint with the following code:

```
async def get_drive_item():
    worksheet = await (graph_client
                  .drives.by_drive_id(drive_id)
                  .items.by_drive_item_id(item_id)
                  .workbook.worksheets
                  .by_workbook_worksheet_id(sheet_name)
                  .used_range
                  .get()
    )
    print(worksheet)
asyncio.run(get_drive_item())
```

Error occurs:
```
Traceback (most recent call last):
  File "/Users/sam.yuen/Desktop/code/test/test.py", line 37, in <module>
    asyncio.run(get_drive_item())
  File "/Users/sam.yuen/opt/anaconda3/envs/deepwys-py38/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/sam.yuen/opt/anaconda3/envs/deepwys-py38/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/sam.yuen/Desktop/code/test/test.py", line 28, in get_drive_item
    worksheet = await (graph_client
  File "/Users/sam.yuen/opt/anaconda3/envs/deepwys-py38/lib/python3.8/site-packages/msgraph/generated/drives/item/items/item/workbook/worksheets/item/used_range/used_range_request_builder.py", line 50, in get
    return await self.request_adapter.send_async(request_info, WorkbookRange, error_mapping)
  File "/Users/sam.yuen/opt/anaconda3/envs/deepwys-py38/lib/python3.8/site-packages/kiota_http/httpx_request_adapter.py", line 190, in send_async
    value = root_node.get_object_value(parsable_factory)
  File "/Users/sam.yuen/opt/anaconda3/envs/deepwys-py38/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 218, in get_object_value
    self._assign_field_values(result)
  File "/Users/sam.yuen/opt/anaconda3/envs/deepwys-py38/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 289, in _assign_field_values
    item_additional_data[field_name] = self.try_get_anything(field_value)
  File "/Users/sam.yuen/opt/anaconda3/envs/deepwys-py38/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 304, in try_get_anything
    return list(map(self.try_get_anything, value))
  File "/Users/sam.yuen/opt/anaconda3/envs/deepwys-py38/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 304, in try_get_anything
    return list(map(self.try_get_anything, value))
  File "/Users/sam.yuen/opt/anaconda3/envs/deepwys-py38/lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 312, in try_get_anything
    datetime_obj = pendulum.parse(value)
  File "/Users/sam.yuen/opt/anaconda3/envs/deepwys-py38/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/Users/sam.yuen/opt/anaconda3/envs/deepwys-py38/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/Users/sam.yuen/opt/anaconda3/envs/deepwys-py38/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/Users/sam.yuen/opt/anaconda3/envs/deepwys-py38/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 116, in _parse
    return _parse_iso8601_interval(text)
  File "/Users/sam.yuen/opt/anaconda3/envs/deepwys-py38/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 221, in _parse_iso8601_interval
    elif last[0] == "P":
IndexError: string index out of range
```

### Expected behavior

return the data from get method

### How to reproduce

# Get the used range
async def get_drive_item():
    worksheet = await (graph_client
                  .drives.by_drive_id(drive_id)
                  .items.by_drive_item_id(item_id)
                  .workbook.worksheets
                  .by_workbook_worksheet_id(sheet_name)
                  .used_range
                  .get()
    )
    print(worksheet)
asyncio.run(get_drive_item())

### SDK Version

1.3.1

### Latest version known to work for scenario above?

1.3.0

### Known Workarounds

Same issue before but fixed  #531 . Now the issue occurs again in the version 1.3.1 but not in version 1.3.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by shemogumbe** [comment]
Hello @SamYuen101234 thanks for using the SDK and for reporting this.

This could possibly be related to https://github.com/microsoftgraph/msgraph-sdk-python/issues/164, however, looking at the traceback, It looks like there is an error at json serialization - Could you be aware of the column raising this, is it a datetime column or a numeric column, tip - check for numeric string character columns or datetime  columns to help isolate and see if this is related to https://github.com/microsoftgraph/msgraph-sdk-python/issues/881
