### ISSUE TITLE
lazy import not found - django watch file's reload

### ISSUE THREAD

**Issue by harold-williams** [microsoftgraph/msgraph-sdk-python#96]
When running django locally using the runserver command and the following version installed:
```
msgraph-sdk==1.0.0a9
Django==4.1
```

I receive the following error:
```
System check identified no issues (0 silenced).
February 11, 2023 - 11:18:08
Django version 4.1
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/home/XXXXXX/XXXXXXX/manage.py", line 22, in <module>
    main()
  File "/home/XXXXXX/XXXXXXX/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/XXXXXX/.virtualenvs/XXXXXXX/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/XXXXXX/.virtualenvs/XXXXXXX/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/XXXXXX/.virtualenvs/XXXXXXX/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/XXXXXX/.virtualenvs/XXXXXXX/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 74, in execute
    super().execute(*args, **options)
  File "/home/XXXXXX/.virtualenvs/XXXXXXX/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/home/XXXXXX/.virtualenvs/XXXXXXX/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 111, in handle
    self.run(**options)
  File "/home/XXXXXX/.virtualenvs/XXXXXXX/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 118, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "/home/XXXXXX/.virtualenvs/XXXXXXX/lib/python3.10/site-packages/django/utils/autoreload.py", line 680, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "/home/XXXXXX/.virtualenvs/XXXXXXX/lib/python3.10/site-packages/django/utils/autoreload.py", line 661, in start_django
    reloader.run(django_main_thread)
  File "/home/XXXXXX/.virtualenvs/XXXXXXX/lib/python3.10/site-packages/django/utils/autoreload.py", line 344, in run
    self.run_loop()
  File "/home/XXXXXX/.virtualenvs/XXXXXXX/lib/python3.10/site-packages/django/utils/autoreload.py", line 350, in run_loop
    next(ticker)
  File "/home/XXXXXX/.virtualenvs/XXXXXXX/lib/python3.10/site-packages/django/utils/autoreload.py", line 390, in tick
    for filepath, mtime in self.snapshot_files():
  File "/home/XXXXXX/.virtualenvs/XXXXXXX/lib/python3.10/site-packages/django/utils/autoreload.py", line 411, in snapshot_files
    for file in self.watched_files():
  File "/home/XXXXXX/.virtualenvs/XXXXXXX/lib/python3.10/site-packages/django/utils/autoreload.py", line 304, in watched_files
    yield from iter_all_python_module_files()
  File "/home/XXXXXX/.virtualenvs/XXXXXXX/lib/python3.10/site-packages/django/utils/autoreload.py", line 115, in iter_all_python_module_files
    modules = tuple(
  File "/home/XXXXXX/.virtualenvs/XXXXXXX/lib/python3.10/site-packages/django/utils/autoreload.py", line 118, in <genexpr>
    if not isinstance(m, weakref.ProxyTypes)
  File "/usr/lib/python3.10/importlib/util.py", line 247, in __getattribute__
    self.__spec__.loader.exec_module(self)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/XXXXXX/.virtualenvs/XXXXXXX/lib/python3.10/site-packages/msgraph/generated/identity_governance/entitlement_management/assignments/item/access_package_assignment_item_request_builder.py", line 16, in <module>
    target_request_builder = lazy_import('msgraph.generated.identity_governance.entitlement_management.assignments.item.target.target_request_builder')
  File "/home/XXXXXX/.virtualenvs/XXXXXXX/lib/python3.10/site-packages/kiota_abstractions/utils.py", line 24, in lazy_import
    spec = importlib.util.find_spec(name)
  File "/usr/lib/python3.10/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'msgraph.generated.identity_governance.entitlement_management.assignments.item.target'
```

It appears that the lazy import in:
https://github.com/microsoftgraph/msgraph-sdk-python/blob/c4ead1cfc12012ed99749a7f774ba54515cd9075/msgraph/generated/identity_governance/entitlement_management/assignments/item/access_package_assignment_item_request_builder.py#L16

is pointing at a non-existent kiota generated instance.

Let me know if you need anymore info.

Temporary solution: removing/commenting this import, then the application is able to run fine, or adding the `--noreload` cli argument also prevent the django watch files from trying to resolve this path.

**Comment by samwelkanda** [comment]
Hi @harold-williams 

Thank you for reporting the above issue. We have since moved away from lazy imports in favor of delayed/local imports. This resolves the above problem of path name conflicts and enables IDE autocomplete to help with discovery. Please upgrade to the latest version and let us know if you face any further issues.
